### ISSUE TITLE
compile error for stolen UIKit header file 

### ISSUE THREAD

**Issue by SSebo** [jankaltoun/TastyMarzipan#1]
Follow your amazing blog instructions, but run on macOS 10.14.3 and xcode 10.1,
compiler complains about UIKit header file which in stolen frameworks folder.

<img width="804" alt="screen shot 2019-01-18 at 9 07 51 am" src="https://user-images.githubusercontent.com/5784607/51358976-8d889800-1b00-11e9-8f0e-d0e21c4a6a20.png">

**Comment by jankaltoun** [comment]
Hi, ah yes, that is true. This approach is now outdated in favour of Marzipanify (https://github.com/steventroughtonsmith/marzipanify) by Steve Troughton-Smith.

I suggest to give this tool a try 🙂.
